### ISSUE TITLE
fr: slide: "Ascenceur" is spelled wrong, I think.

### ISSUE THREAD

**Issue by dflock** [primefaces/primelocale#101]
"Ascenceur" isn't a word afaict, and looks like it might be a misspelling of "Ascenseur", which would translate as "Elevator", according to Google Translate.

I'm not sure what the context for "slide" actually is, so not sure what the correct translation would be.

**Comment by melloware** [comment]
It used here https://primevue.org/carousel/ like which Slide number of a slide show...

**Comment by dflock** [comment]
Then the word should be 'diapositive' - see PR.
