### ISSUE TITLE
Any docs to show how to use this repo?

### ISSUE THREAD

**Issue by xiangnanscu** [primefaces/primelocale#110]
for example, if I want to use zh?

**Comment by melloware** [comment]
Which Prime Library are you using?

**Comment by xiangnanscu** [comment]
primevue

**Comment by melloware** [comment]
Yep just copy the `zh` file and follow these primevue instructions: https://primevue.org/configuration/#setlocale

**Comment by xiangnanscu** [comment]
OK. thanks.

**Comment by humbertleonardo** [comment]
It's still not clear to me, what folder do I copy the file to? What exactly do I change when importing from PrimeVUe?

**Comment by humbertleonardo** [comment]
When I try to import the pt.json file, I receive the following error in the console

 ERROR  Cannot restart nuxt:  Maximum call stack size exceeded                                   11:24:02 AM
 
 
![image](https://github.com/primefaces/primelocale/assets/57204453/619407c9-d0a6-46b9-8855-f394f7e1adfa)

**Comment by melloware** [comment]
@humbertleonardo here is a Vue I8LN starter: https://github.com/primefaces/primevue-examples/tree/main/vue-i18n

**Comment by humbertleonardo** [comment]
I ended up solving it another way, instead of saving it in JSON, I saved it as JS and imported the JS file, that's how it worked. Thanks!
