### ISSUE TITLE
'Now' label is missing

### ISSUE THREAD

**Issue by majkers** [primefaces/primelocale#116]
Please refer to https://github.com/primefaces/primefaces/issues/10754

When showButtonBar and only a date it should be `Today` label.
When showButtonbar and using Time it should be `Now` label

**Comment by majkers** [comment]
[primefaces-test-master.zip](https://github.com/primefaces/primelocale/files/12893516/primefaces-test-master.zip)


Reproducer You asked for

**Comment by melloware** [comment]
@majkers what is your native tongue and what is "Now" so I can add it here?

**Comment by majkers** [comment]
My native is polish and it is 'Teraz'
