### ISSUE TITLE
cannot make it work, an example use would help

### ISSUE THREAD

**Issue by petitkriket** [primefaces/primelocale#119]
Hello,

I am trying to lokalize an app using a community locale.

I cannot make it work through the global registration api (prime vue app wide configuration object)

i tried 

 - community package import and global registration (does not work)
 - handmade message global registration (does not work)
 - component local override (works)

Here is a reproduction example with primevue.
https://stackblitz.com/edit/ejwndf?file=src%2FApp.vue,src%2Fmain.js%3AL117,src%2Ffr.json

does somewhy have an idea why global API does not work as it is ?

I would gladly contribute and add installation examples to primereact and primevue or to this package directly :)

**Comment by melloware** [comment]
I don't use PrimeVue but React is similar and here is an example of switching to Russian Locale:

https://stackblitz.com/edit/react-mt3y5i?file=src%2FApp.js

**Comment by petitkriket** [comment]
the way locale is loaded is a bit different with Vue. In the following example,  I am strictly following the docs by recreating the 3 provided "ways" to do it but it actually does not work 😅

I will create an issue into primevue repository as it seem to be framework specific, tks :)
