### ISSUE TITLE
Wrong country code for Denmark. Its 'dk' not 'da'

### ISSUE THREAD

**Issue by Mat3uszkek** [primefaces/primelocale#165]
Can we switch it?

**Comment by melloware** [comment]
Yes we can sorry i was going on the Java locale which has it as `da`  https://www.localeplanet.com/java/da-DK/index.html

Here for JavaScript its confusing also: https://simplelocalize.io/data/locale-code/da-DK/

it says the Language code is "da".    What happens in Chrome/Edge console if you type `navigator.language`

![image](https://github.com/primefaces/primelocale/assets/4399574/669bbb34-c03f-4ac8-902f-0e588cda854e)

**Comment by melloware** [comment]
@Mat3uszkek is it safe to close this?
