### ISSUE TITLE
How to apply the translations installed via npm

### ISSUE THREAD

**Issue by tabarnouche** [primefaces/primelocale#172]
So far I've managed to install the repo via npm thanks to https://github.com/primefaces/primelocale/issues/71#issuecomment-2102665554.

But now I don't know how to import and apply the json file to my PrimeVue project.

Does anyone know the way?
Shold I anyway copy and paste it to the locale key in app.js?

**Comment by melloware** [comment]
Here is a CodeSandbox showing you exactly how to do it: https://codesandbox.io/p/devbox/primevue-locale-loader-gxm2ct?file=%2Fsrc%2FApp.vue

**Comment by tabarnouche** [comment]
Thanks!
