### ISSUE TITLE
Question: How to implement locale in primereact?

### ISSUE THREAD

**Issue by DanielFerreira137** [primefaces/primelocale#182]
Hello, I have this project an I wanted to change the locale languague but im having troubles.
I'm using typescript and when trying to implement locale this error appears:

Error: (0 , primereact_api__WEBPACK_IMPORTED_MODULE_5__.addLocale) is not a function

**Comment by melloware** [comment]
Here is a PrimeReact example using the Hungarian language.

https://stackblitz.com/edit/react-zyv3qr-zzp7un?file=src%2Fprimelocale%2Fhu.json,src%2Findex.js,src%2FApp.js
