### ISSUE TITLE
1.2.0 version causes build fails due to bs.json syntax error.

### ISSUE THREAD

**Issue by dencs08** [primefaces/primelocale#197]
Hi, 1.2.0 introduced the new translation file which causes build errors due to comma character being in a wrong place.

To inspect the error please download the sourcode 1.2.0 from [releases](https://github.com/primefaces/primelocale/releases/tag/1.2.0) open the bs.json file and go to the line 47

```
     "nextYear": "Next Year",{
    "bs":{
```

**Comment by melloware** [comment]
Yep I fixed it in main and need to push a 1.2.1.  Will do it tomorrow.

**Comment by melloware** [comment]
1.2.1 is on NPM now!
