### ISSUE TITLE
Publish PrimeLocale to npm?

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [primefaces/primelocale#71]
Would be simpler to use and update to newer versions.

**Comment by melloware** [comment]
Also has been mentioned on Discord and PrimeTek has put it on their list!

**Comment by C0ZEN** [comment]
I am so surprised that this is not the case already 🤔

**Comment by melloware** [comment]
Do you have instructions on how your included using GitHub syntax and then I can test and add a package.json. Thanks!

**Comment by Anders142536** [comment]
Oh of course, I should have included a link to the documentation in the first message already:
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#github-urls

**Comment by melloware** [comment]
OK I added package.json but didn't test it yet if you want to test it: https://github.com/primefaces/primelocale/blob/main/package.json

**Comment by Anders142536** [comment]
The only issue we see in this solution now is that our company internal caches for depenency packages will not work with github dependencies. I guess other people will have the same issue, so maybe uploading it to npm repo still makes sense.

**Comment by melloware** [comment]
Agreed but according to the docs you can add a commit ID hash in your url and it will pull that version.  Still not as good as in NPM but better   than nothing

**Comment by melloware** [comment]
React example how to use PrimeLocale: https://stackblitz.com/edit/react-3glwrd?file=src%2FApp.tsx,package.json,src%2Findex.tsx

**Comment by jerlam06** [comment]
> Agreed but according to the docs you can add a commit ID hash in your url and it will pull that version. Still not as good as in NPM but better than nothing

@melloware What docs are you referring to please?

**Comment by melloware** [comment]
Sorry it's in the NPM docs for using just a git project like above. I had no idea you could do that. 

PrimeTek is aware and is working on getting this released for real on NPMJS.

**Comment by melloware** [comment]
It is and I asked him to take it down. It's way out of date and should be released by PrimeTek.

**Comment by iwnow** [comment]
npm i github:primefaces/primelocale

**Comment by alexef** [comment]
> PrimeTek is aware and is working on getting this released for real on NPMJS.

is there another issue I can track?

**Comment by melloware** [comment]
@cagataycivici any update on this?

**Comment by melloware** [comment]
1.0.0 is now published in NPM!

**Comment by dbelob** [comment]
> 1.0.0 is now published in NPM!

Thanks!

@melloware What is the future release strategy for new versions?
* new version after each new string resource
* new version every month (quarter, year) if there are changes
* another variant

**Comment by dbelob** [comment]
> doing it on every change feels right to me.

I agree with this opinion.

May be
* patch (1.0.0 -> 1.0.1) – any changes without new string resources
* minor (1.0.0 -> 1.1.0) – new string resource (-s) with/without other changes
* major (1.0.0 -> 2.0.0) – lots of new string resources

**Comment by melloware** [comment]
totally agree with that `semver` approach!
