### ISSUE TITLE
dateFormat in es.json is incorrect

### ISSUE THREAD

**Issue by RichardMcElroy** [primefaces/primelocale#79]
In the Spanish translation (es.json) the date format is currently:
"dateFormat": "dd/mm/yyyy"
This shows the year twice. It should be
"dateFormat": "dd/mm/yy",

**Comment by melloware** [comment]
Thanks for the report I just fixed it.

**Comment by melloware** [comment]
I also fixed ca.json which is the Catalan language which I assume would have the same date format?

**Comment by RichardMcElroy** [comment]
Perfect - Thanks!!
