### ISSUE TITLE
Context for translation

### ISSUE THREAD

**Issue by tavoda** [primefaces/primelocale#8]
Can you please provide some context where translations for "weak", "medium" and "strong" is used because correct translation is not so straightforward and sometimes depends on surrounding context.

**Comment by mertsincan** [comment]
Hi,

Sorry for the delayed response! This link can help to you;
https://codesandbox.io/s/primereact-locale-demo-wbnm5?file=/src/demo/LocaleDemo.js

You can review Password component for "weak", "medium" and "strong" texts according to the selected language.

Best Regards,
