### ISSUE TITLE
Invalid JSON files are not importable - because of comments

### ISSUE THREAD

**Issue by dflock** [primefaces/primelocale#82]
The following JSON files have comments in:

- fr.json
- pl.json
- nb-no.json
- id.json
- fa.json
- en-gb.json
- en-au.json

These are therefore invalid, and trying to `import` them into code will fail.

This was pretty surprising to me - how else are people using these files, if not importing them? I'm using them like this:

```js
import primeLocaleEn from '../../primelocale/en.json'
import primeLocaleFr from '../../primelocale/fr.json'

export const primeLocales = { ...primeLocaleEn, ...primeLocaleFr }
```

and then in my language switcher component:

```js
import { usePrimeVue } from 'primevue/config'
const primevue = usePrimeVue()

primevue.config.locale = primeLocales[selectedLanguage]
```

But this fails with the `fr.json` file, because it's not a valid JSON file - until I removed the comments.

Am I doing this wrong?

**Comment by melloware** [comment]
Nope you are right the comments need to be removed.  Feel free to submit a PR

**Comment by melloware** [comment]
I just fixed them all

**Comment by dflock** [comment]
Awesome, too quick for me, thanks!
